# Skip known fileds, that not nessesary
ignore:
  - host
  - advisoryHostFQDNs
  - version
  - process
  - pid
  - uptime
  - uptimeMillis
  - uptimeEstimate
  - localTime
  - extra_info
  - sharding

rules:
  # asserts.regular    0
  # asserts.warning    0
  # asserts.msg        0
  # asserts.user       4
  # asserts.rollovers  0
  # Export as mongo_server_asserts{type="regular"} 1
  - key: asserts
    values:
      label: type
      skip:
        - rollovers
    metric: asserts
    type: counter



# connections.current  7
# connections.available  197
# connections.totalCreated  148
# extra_info.note  fields vary by platform
# extra_info.page_faults  894
# network.bytesIn  879093
# network.bytesOut  1835110
# network.numRequests  15299
# opcounters.insert  1
# opcounters.query  114
# opcounters.update  3
# opcounters.delete  0
# opcounters.getmore  0
# opcounters.command  15186
# sharding.configsvrConnectionString  yopp-air.local:27182,yopp-air.local:27183,yopp-air.local:27184
# mem.bits  64
# mem.resident  7
# mem.virtual  2434
# mem.supported  true
# metrics.commands.<UNKNOWN>  0
# metrics.commands._isSelf.failed  0
# metrics.commands._isSelf.total  0
# metrics.commands._mergeAuthzCollections.failed  0
# metrics.commands._mergeAuthzCollections.total  0
# metrics.commands.addShard.failed  0
# metrics.commands.addShard.total  3
# metrics.commands.aggregate.failed  0
# metrics.commands.aggregate.total  11
# metrics.commands.applyOps.failed  0
# metrics.commands.applyOps.total  0
# metrics.commands.authSchemaUpgrade.failed  0
# metrics.commands.authSchemaUpgrade.total  0
# metrics.commands.authenticate.failed  0
# metrics.commands.authenticate.total  0
# metrics.commands.availableQueryOptions.failed  0
# metrics.commands.availableQueryOptions.total  0
# metrics.commands.buildInfo.failed  0
# metrics.commands.buildInfo.total  20
# metrics.commands.collMod.failed  0
# metrics.commands.collMod.total  0
# metrics.commands.collStats.failed  0
# metrics.commands.collStats.total  0
# metrics.commands.compact.failed  0
# metrics.commands.compact.total  0
# metrics.commands.connPoolStats.failed  0
# metrics.commands.connPoolStats.total  0
# metrics.commands.connPoolSync.failed  0
# metrics.commands.connPoolSync.total  0
# metrics.commands.connectionStatus.failed  0
# metrics.commands.connectionStatus.total  0
# metrics.commands.convertToCapped.failed  0
# metrics.commands.convertToCapped.total  0
# metrics.commands.copydb.failed  0
# metrics.commands.copydb.total  0
# metrics.commands.count.failed  0
# metrics.commands.count.total  3
# metrics.commands.create.failed  0
# metrics.commands.create.total  0
# metrics.commands.createIndexes.failed  0
# metrics.commands.createIndexes.total  0
# metrics.commands.createRole.failed  0
# metrics.commands.createRole.total  0
# metrics.commands.createUser.failed  0
# metrics.commands.createUser.total  0
# metrics.commands.currentOp.failed  0
# metrics.commands.currentOp.total  0
# metrics.commands.dataSize.failed  0
# metrics.commands.dataSize.total  0
# metrics.commands.dbStats.failed  0
# metrics.commands.dbStats.total  0
# metrics.commands.delete.failed  0
# metrics.commands.delete.total  0
# metrics.commands.distinct.failed  0
# metrics.commands.distinct.total  0
# metrics.commands.drop.failed  0
# metrics.commands.drop.total  1
# metrics.commands.dropAllRolesFromDatabase.failed  0
# metrics.commands.dropAllRolesFromDatabase.total  0
# metrics.commands.dropAllUsersFromDatabase.failed  0
# metrics.commands.dropAllUsersFromDatabase.total  0
# metrics.commands.dropDatabase.failed  0
# metrics.commands.dropDatabase.total  0
# metrics.commands.dropIndexes.failed  0
# metrics.commands.dropIndexes.total  0
# metrics.commands.dropRole.failed  0
# metrics.commands.dropRole.total  0
# metrics.commands.dropUser.failed  0
# metrics.commands.dropUser.total  0
# metrics.commands.enableSharding.failed  0
# metrics.commands.enableSharding.total  0
# metrics.commands.eval.failed  0
# metrics.commands.eval.total  0
# metrics.commands.explain.failed  0
# metrics.commands.explain.total  0
# metrics.commands.features.failed  0
# metrics.commands.features.total  0
# metrics.commands.filemd5.failed  0
# metrics.commands.filemd5.total  0
# metrics.commands.find.failed  0
# metrics.commands.find.total  114
# metrics.commands.findAndModify.failed  0
# metrics.commands.findAndModify.total  0
# metrics.commands.flushRouterConfig.failed  0
# metrics.commands.flushRouterConfig.total  0
# metrics.commands.forceerror.failed  0
# metrics.commands.forceerror.total  0
# metrics.commands.fsync.failed  0
# metrics.commands.fsync.total  0
# metrics.commands.geoNear.failed  0
# metrics.commands.geoNear.total  0
# metrics.commands.getCmdLineOpts.failed  0
# metrics.commands.getCmdLineOpts.total  0
# metrics.commands.getLastError.failed  0
# metrics.commands.getLastError.total  6
# metrics.commands.getLog.failed  0
# metrics.commands.getLog.total  1
# metrics.commands.getMore.failed  0
# metrics.commands.getMore.total  0
# metrics.commands.getParameter.failed  0
# metrics.commands.getParameter.total  0
# metrics.commands.getPrevError.failed  0
# metrics.commands.getPrevError.total  0
# metrics.commands.getShardMap.failed  0
# metrics.commands.getShardMap.total  0
# metrics.commands.getShardVersion.failed  0
# metrics.commands.getShardVersion.total  0
# metrics.commands.getnonce.failed  0
# metrics.commands.getnonce.total  0
# metrics.commands.grantPrivilegesToRole.failed  0
# metrics.commands.grantPrivilegesToRole.total  0
# metrics.commands.grantRolesToRole.failed  0
# metrics.commands.grantRolesToRole.total  0
# metrics.commands.grantRolesToUser.failed  0
# metrics.commands.grantRolesToUser.total  0
# metrics.commands.group.failed  0
# metrics.commands.group.total  0
# metrics.commands.hostInfo.failed  0
# metrics.commands.hostInfo.total  0
# metrics.commands.insert.failed  0
# metrics.commands.insert.total  1
# metrics.commands.invalidateUserCache.failed  0
# metrics.commands.invalidateUserCache.total  0
# metrics.commands.isMaster.failed  0
# metrics.commands.isMaster.total  4345
# metrics.commands.isdbgrid.failed  0
# metrics.commands.isdbgrid.total  0
# metrics.commands.killCursors.failed  0
# metrics.commands.killCursors.total  0
# metrics.commands.killOp.failed  0
# metrics.commands.killOp.total  0
# metrics.commands.listCollections.failed  0
# metrics.commands.listCollections.total  4
# metrics.commands.listCommands.failed  0
# metrics.commands.listCommands.total  0
# metrics.commands.listDatabases.failed  0
# metrics.commands.listDatabases.total  33
# metrics.commands.listIndexes.failed  0
# metrics.commands.listIndexes.total  0
# metrics.commands.listShards.failed  0
# metrics.commands.listShards.total  0
# metrics.commands.logRotate.failed  0
# metrics.commands.logRotate.total  0
# metrics.commands.logout.failed  0
# metrics.commands.logout.total  0
# metrics.commands.mapReduce.failed  0
# metrics.commands.mapReduce.total  0
# metrics.commands.mergeChunks.failed  0
# metrics.commands.mergeChunks.total  0
# metrics.commands.moveChunk.failed  0
# metrics.commands.moveChunk.total  0
# metrics.commands.movePrimary.failed  0
# metrics.commands.movePrimary.total  0
# metrics.commands.netstat.failed  0
# metrics.commands.netstat.total  0
# metrics.commands.ping.failed  0
# metrics.commands.ping.total  10690
# metrics.commands.planCacheClear.failed  0
# metrics.commands.planCacheClear.total  0
# metrics.commands.planCacheClearFilters.failed  0
# metrics.commands.planCacheClearFilters.total  0
# metrics.commands.planCacheListFilters.failed  0
# metrics.commands.planCacheListFilters.total  0
# metrics.commands.planCacheListPlans.failed  0
# metrics.commands.planCacheListPlans.total  0
# metrics.commands.planCacheListQueryShapes.failed  0
# metrics.commands.planCacheListQueryShapes.total  0
# metrics.commands.planCacheSetFilter.failed  0
# metrics.commands.planCacheSetFilter.total  0
# metrics.commands.profile.failed  0
# metrics.commands.profile.total  0
# metrics.commands.reIndex.failed  0
# metrics.commands.reIndex.total  0
# metrics.commands.removeShard.failed  0
# metrics.commands.removeShard.total  0
# metrics.commands.renameCollection.failed  0
# metrics.commands.renameCollection.total  0
# metrics.commands.repairDatabase.failed  0
# metrics.commands.repairDatabase.total  0
# metrics.commands.replSetGetStatus.failed  4
# metrics.commands.replSetGetStatus.total  4
# metrics.commands.resetError.failed  0
# metrics.commands.resetError.total  0
# metrics.commands.revokePrivilegesFromRole.failed  0
# metrics.commands.revokePrivilegesFromRole.total  0
# metrics.commands.revokeRolesFromRole.failed  0
# metrics.commands.revokeRolesFromRole.total  0
# metrics.commands.revokeRolesFromUser.failed  0
# metrics.commands.revokeRolesFromUser.total  0
# metrics.commands.rolesInfo.failed  0
# metrics.commands.rolesInfo.total  0
# metrics.commands.saslContinue.failed  0
# metrics.commands.saslContinue.total  0
# metrics.commands.saslStart.failed  0
# metrics.commands.saslStart.total  0
# metrics.commands.serverStatus.failed  0
# metrics.commands.serverStatus.total  41
# metrics.commands.setParameter.failed  0
# metrics.commands.setParameter.total  0
# metrics.commands.shardCollection.failed  0
# metrics.commands.shardCollection.total  0
# metrics.commands.shardConnPoolStats.failed  0
# metrics.commands.shardConnPoolStats.total  0
# metrics.commands.shutdown.failed  0
# metrics.commands.shutdown.total  0
# metrics.commands.split.failed  0
# metrics.commands.split.total  0
# metrics.commands.splitVector.failed  0
# metrics.commands.splitVector.total  0
# metrics.commands.update.failed  0
# metrics.commands.update.total  3
# metrics.commands.updateRole.failed  0
# metrics.commands.updateRole.total  0
# metrics.commands.updateUser.failed  0
# metrics.commands.updateUser.total  0
# metrics.commands.usersInfo.failed  0
# metrics.commands.usersInfo.total  0
# metrics.commands.validate.failed  0
# metrics.commands.validate.total  0
# metrics.commands.whatsmyuri.failed  0
# metrics.commands.whatsmyuri.total  20
# metrics.cursor.open.multiTarget  0
# metrics.cursor.open.singleTarget  0
# metrics.cursor.open.pinned  0
# metrics.cursor.open.total  0
# metrics.getLastError.wtime.num  0
# metrics.getLastError.wtime.totalMillis  0
