version: 1

# To give it a try get `mtools` (https://github.com/rueckstiess/mtools) and
# then launch your small cluster:
#
# mlaunch init --replicaset --sharded hot warm cold --config 3 --mongos 3 --port 27170 --hostname localhost
#
# Note: you must specify the nodes in the configuration using the hostnames,
# not the IP address, becuse mongo uses hostnames in nodes names.

mongo:
  # Only `sharded` is currently supported
  mode: sharded

  # List of mongos instanes to connect
  mongos:
    - localhost:27170
    - localhost:27171
    - localhost:27172

  # Shard topology
  shards:
    - localhost:27173
    - localhost:27174
    - localhost:27175
    - localhost:27176
    - localhost:27177
    - localhost:27178
    - localhost:27179
    - localhost:27180
    - localhost:27181

  # List of config servers
  configs:
    - localhost:27182
    - localhost:27183
    - localhost:27184

# Namespaces to export.
#
# For example, to export metrics only from one collection `foo` from database
# `bar` specify `bar.foo`. To export all collections from `bar` just specify
# `bar.*`.
#
# If no namespace given, all discovered namespaces will be exported.
# namespaces:
#  - foo.*

# Set to true if you want to export index metrics as well.
include_index: true
