version: 1

# To give it a try get `mtools` (https://github.com/rueckstiess/mtools) and
# then launch your small cluster:
#
# mlaunch init --replicaset --sharded hot warm cold --config 3 --mongos 3 --port 27170 --hostname localhost --auth --csrs
#
# Note: you must specify the nodes in the configuration using the hostnames,
# not the IP address, becuse mongo uses hostnames in nodes names.

mongo:
  # Only `sharded` is currently supported
  mode: sharded

  # List of mongos instanes to connect
  mongos:
    - mongodb://user:password@localhost:27170
    - mongodb://user:password@localhost:27171
    - mongodb://user:password@localhost:27172

  # Shard topology
  shards:
    - mongodb://user:password@localhost:27173
    - mongodb://user:password@localhost:27174
    - mongodb://user:password@localhost:27175
    - mongodb://user:password@localhost:27176
    - mongodb://user:password@localhost:27177
    - mongodb://user:password@localhost:27178
    - mongodb://user:password@localhost:27179
    - mongodb://user:password@localhost:27180
    - mongodb://user:password@localhost:27181

  # List of config servers
  configs:
    - mongodb://user:password@localhost:27182
    - mongodb://user:password@localhost:27183
    - mongodb://user:password@localhost:27184

# Namespaces to export.
#
# For example, to export metrics only from one collection `foo` from database
# `bar` specify `bar.foo`. To export all collections from `bar` just specify
# `bar.*`.
#
# If no namespace given, all discovered namespaces will be exported.
# namespaces:
#  - foo.*

# Set to true if you want to export index metrics as well.
include_index: true
